swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "irrigacao-api"
  contact:
    email: ""
host: "localhost:3000"
basePath: "/"
tags:
- name: "irrigacao"
  description: "Irrigação"
- name: "user"
  description: "User"
- name: "inpe"
  description: "Inpe"
paths:
  /irrigacao:
    get:
      tags:
      - "irrigacao"
      summary: "Health check"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"

  /user/login:
    post:
      tags:
      - "user"
      summary: "Login"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/AuthLogin"
  /user/new:
    post:
      tags:
      - "user"
      summary: "Create new user"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/User"
  /user/all:
    get:
      tags:
      - "user"
      summary: "List all users"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
  /user/auth:
    post:
      tags:
      - "user"
      summary: "Authenticate token"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/AuthToken"
  
  /inpe/listaCidades:
    get:
      tags:
      - "inpe"
      summary: "List all"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
  /inpe/listaCidades/{city}:
    get:
      tags:
      - "inpe"
      summary: "Search city"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
      parameters:
        - in: "path"
          name: "city"
          type: "string"
  /inpe/cidade/previsao/{city}:
    get:
      tags:
      - "inpe"
      summary: "Weather by city for 4 days"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
      parameters:
        - in: "path"
          name: "city"
          type: "string"
  
definitions:
  AuthLogin:
    type: "object"
    required:
      - "username"
      - "password"    
    properties:
      username:
        type: "string"
      password:
        type: "string"
  AuthToken:
    type: "object"
    required:
      - "token"
    properties:
      token:
        type: "string"
  User:
    type: "object"
    required:
      - "username"
      - "password"
    properties:
      name:
        type: "string"
      username:
        type: "string"
      password:
        type: "string"
      mail:
        type: "string"
      city:
        type: "integer"