swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "irrigacao-api"
  contact:
    email: ""
host: "localhost:3000"
basePath: "/"
tags:
- name: "irrigacao"
  description: "Irrigação"
- name: "user"
  description: "User"
- name: "inpe"
  description: "Inpe"
paths:
  /irrigacao:
    get:
      tags:
      - "irrigacao"
      summary: "[APS] Health check"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
  /irrigacao/verifica:
    get:
      tags:
      - "irrigacao"
      summary: "[APS] Verify status irrigation"
      description: ""
      security:
        - jwt: []
      responses:
        200:
          description: "OK"
        401:
          description: "Unauthorized"
        500:
          description: "Internal Server Error"
  /irrigacao/controla/{estado}:
    put:
      tags:
      - "irrigacao"
      summary: "[APS] Update status irrigation"
      description: ""
      security:
        - jwt: []
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        500:
          description: "Internal Server Error"
      parameters:
        - in: path
          name: estado
          schema:
            type: string
          required: true
          description: Send "on" to activate or "off" to deactivate

  /user/login:
    post:
      tags:
      - "user"
      summary: "Login"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/AuthLogin"
  /user/new:
    post:
      tags:
      - "user"
      summary: "Create new user"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/User"
  /user/update:
    put:
      tags:
      - "user"
      summary: "Update me"
      description: ""
      security:
        - jwt: []
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/User"
  /user/me:
    get:
      tags:
      - "user"
      summary: "Return me user"
      description: ""
      security:
        - jwt: []
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
  /user/all:
    get:
      tags:
      - "user"
      summary: "List all users"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
  /user/auth:
    post:
      tags:
      - "user"
      summary: "Authenticate token"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/AuthToken"
            
  /inpe/listaCidades/{city}:
    get:
      tags:
      - "inpe"
      summary: "Search city"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
      parameters:
        - in: "path"
          name: "city"
          type: "string"
  /inpe/cidade/previsao/{city}:
    get:
      tags:
      - "inpe"
      summary: "Weather by city for 4 days"
      description: ""
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
      parameters:
        - in: "path"
          name: "city"
          type: "string"

securityDefinitions:
  jwt:
    in: "header"
    type: "apiKey"
    name: "Authorization"
  
definitions:
  AuthLogin:
    type: "object"
    required:
      - "username"
      - "password"    
    properties:
      username:
        type: "string"
      password:
        type: "string"
  AuthToken:
    type: "object"
    required:
      - "token"
    properties:
      token:
        type: "string"
  User:
    type: "object"
    required:
      - "username"
      - "password"
    properties:
      name:
        type: "string"
      username:
        type: "string"
      password:
        type: "string"
      mail:
        type: "string"
      city:
        type: "object"
        required:
          - "id"
        properties:
          id:
            type: "integer"
          nome:
            type: "string"
          uf:
            type: "string"