version: '3'

services:
  tcc-api:
    image: "node:${NODE_VERSION}"
    container_name: "tcc-api"
    working_dir: /usr/src/api
    volumes:
      - ./api:/usr/src/api
    ports:
      - "${API_PORT}:${API_PORT}"
    links:
      - tcc-mongodb
    depends_on:
      - tcc-mongodb
    networks:
      tcc:
        ipv4_address: ${API_IPV4_ADDRESS}
    environment:
      - PORT=${API_PORT}
      - DB_IPV4_ADDRESS=${DB_IPV4_ADDRESS}
      - DB_USER=${DB_USER} 
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    command: ["npm", "start"]
  tcc-app-mobile:
    image: "node:8.10"
    container_name: "tcc-app-mobile"
    working_dir: /usr/src/app-mobile
    volumes:
      - ./app-mobile:/usr/src/app-mobile
    ports:
      - "${APP_MOBILE_PORT}:${APP_MOBILE_PORT}"
      - "8100:8100"
    networks:
      tcc:
        ipv4_address: ${APP_MOBILE_IPV4_ADDRESS}
    environment:
      - PORT=${APP_MOBILE_PORT}
      - API_IPV4_ADDRESS=${API_IPV4_ADDRESS}
      - API_PORT=${API_PORT}
    command: ["npm", "run", "lab"]
  tcc-mongodb:
    image: mongo:latest
    container_name: "tcc-mongodb"
    volumes:
      - ./db/data:/data/db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      tcc:
        ipv4_address: ${DB_IPV4_ADDRESS}
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="${DB_USER}" 
      - MONGODB_PASS="${DB_PASSWORD}"
    command: mongod --smallfiles --logpath=/dev/null
networks:
  tcc:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}