version: '3'

services:
  tcc-api:
    image: "node:${NODE_VERSION}"
    container_name: "tcc-api"
    working_dir: /usr/src/api
    volumes:
      - ./api:/usr/src/api
    ports:
      - "${API_PORT}:${API_PORT}"
    # links:
    #   - "db:database"
    # depends_on:
    #   - db
    networks:
      tcc:
        ipv4_address: ${API_IPV4_ADDRESS}
    environment:
      - PORT=${API_PORT}
      # - DB_IPV4_ADDRESS=${DB_IPV4_ADDRESS}
      # - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      # - DB_DATABASE=${DB_DATABASE}
    command: ["npm", "start"]
  tcc-app-mobile:
    image: "node:8.10"
    container_name: "tcc-app-mobile"
    working_dir: /usr/src/app-mobile
    volumes:
      - ./app-mobile:/usr/src/app-mobile
    ports:
      - "${APP_MOBILE_PORT}:${APP_MOBILE_PORT}"
      - "8100:8100"
    networks:
      tcc:
        ipv4_address: ${APP_MOBILE_IPV4_ADDRESS}
    environment:
      - PORT=${APP_MOBILE_PORT}
    command: ["npm", "run", "lab"]
#   db:
#     image: "mysql:${MYSQL_VERSION}"
#     container_name: "followup_db"
#     volumes:
#       - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
#     ports:
#       - "${DB_PORT}:3306"
#     networks:
#      followup:
#       ipv4_address: ${DB_IPV4_ADDRESS}
#     environment:
#       MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
#       MYSQL_DATABASE: "${DB_DATABASE}"
networks:
  tcc:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}