version: '3'

services:
  aps-api:
    image: "node:${NODE_VERSION}"
    container_name: "aps-api"
    working_dir: /usr/src/api
    volumes:
      - ./api:/usr/src/api
    ports:
      - "${API_PORT}:${API_PORT}"
    links:
      - aps-mongodb
    depends_on:
      - aps-mongodb
    networks:
      aps:
        ipv4_address: ${API_IPV4_ADDRESS}
    environment:
      - PORT=${API_PORT}
      - DB_IPV4_ADDRESS=${DB_IPV4_ADDRESS}
      - DB_USER=${DB_USER} 
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DUMP_DEMO=${DUMP_DEMO}
    command: ["npm", "start"]
  aps-mongodb:
    image: 'bitnami/mongodb:latest'
    container_name: "aps-mongodb"
    volumes:
      - ./db/data:/data/db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      aps:
        ipv4_address: ${DB_IPV4_ADDRESS}
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="${DB_USER}" 
      - MONGODB_PASS="${DB_PASSWORD}"
networks:
  aps:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}